spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmall?useUnicode=true&characterEncoding=UTF8&serverTimeZone=UTC
    username: root
    password: www.huawei.com

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.deean.tkmapperdemo.bean