spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dnmall?characterEncoding=UTF-8
      username: root
      password: www.huawei.com
springdoc:
  swagger-ui:
    path: /swagger-ui.html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

