spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bookmall?characterEncoding=UTF-8
      username: root
      password: www.huawei.com
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.deean.dnmall.bean
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    com.hexadecimal: debug
